### ISSUE TITLE
Children in header not receiving touch

### ISSUE THREAD

**Issue by LeoJHarris** [DevsDNA/XFParallax#4]
Hi there,

Very cool plugin, regarding the header I tried putting a carousel into the header and I couldn't swipe between them in that.

Is it possible to get touch for children in the header?

**Comment by TMagnum1974** [comment]
Same here - it's really cool, but I also have the problem that header gestures are not recognized.
I assume (!) it's because the body is rendered on top of it and thus any gestures are recognized in the body, only. Dunno if the control is still supported - maybe can find a way to solve it in the source or find an alternative way of achieving the result. I like the control - but maybe doing it separately in own code opens a possibility to get the gestures properly handled again?

**Comment by LeoJHarris** [comment]
@TMagnum1974 Something I didn't try that might work would be setting InputTransparent="True" to the parent layout.

**Comment by LeoJHarris** [comment]
@TMagnum1974  that way it might enable the gesture to be received to children beneath the parallax background, I actually don't need to receive those touch events for what I was doing anymore.

**Comment by TMagnum1974** [comment]
Thanks for the inspiration - I'll give that a try! The control is pretty good otherwise. Will post feedback when I was able to give it a try.

**Comment by gaffkins** [comment]
@TMagnum1974 
Did you resolve problem?

**Comment by TMagnum1974** [comment]
Hi! No, I was not able to resolve it. The way the solution works, there's always that overlap and if you set the body input transparent, the header gets responsive but the body ain't anymore. Need to work on a complete replacement unfortunately - currently I have completely replaced it with a static header and once I completed my main work on the app will see if I find a different solution for the aimed look & feel.

**Comment by LeoJHarris** [comment]
@TMagnum1974 @gaffkins I revised this again since I needed touch working for children in header and if you want to get touch for children in header set `IsEnabled` to false on parentscroll view and header should begin recieving tap gestures, scroll doesnt work in header but can scroll with body, looking at a way to scroll with header also.
